USE [BDMG]
GO

/****** Object:  Table [dbo].[TAB_TAREFA]    Script Date: 11/10/2024 23:25:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TAB_TAREFA](
	[ID_TAREFA] [int] IDENTITY(1,1) NOT NULL,
	[DESC_TAREFA] [varchar](50) NULL,
	[PRIORIDADE] [int] NULL,
	[STATUS] [varchar](20) NULL,
	[DTCONCLUSAO] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_TAREFA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO





/****** SQL do Desafio SQL utilizando SQL Server ******/

SELECT 
COUNT(*) AS TotalTarefas,
CASE 
	WHEN COUNT(CASE WHEN STATUS <> 'FINALIZADA' THEN 1 END) > 0 
	THEN AVG(CASE WHEN STATUS <> 'FINALIZADA' THEN PRIORIDADE END)
ELSE 0 
END AS MediaPrioridadePendentes,
COUNT(CASE WHEN STATUS = 'FINALIZADA' AND DTCONCLUSAO >= DATEADD(DAY, -7, GETDATE()) THEN 1 END) AS TarefasConcluidasUltimos7Dias
FROM 
TAB_TAREFA;
